// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Projects\goProjects\ShortyURL\internal\repository/repository_interface.go

// Package mock_repository is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/dimalewshin98-glitch/ShortyURL/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockRepositoryInterface is a mock of RepositoryInterface interface.
type MockRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryInterfaceMockRecorder
}

// MockRepositoryInterfaceMockRecorder is the mock recorder for MockRepositoryInterface.
type MockRepositoryInterfaceMockRecorder struct {
	mock *MockRepositoryInterface
}

// NewMockRepositoryInterface creates a new mock instance.
func NewMockRepositoryInterface(ctrl *gomock.Controller) *MockRepositoryInterface {
	mock := &MockRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryInterface) EXPECT() *MockRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockRepositoryInterface) Get(ctx context.Context, urlID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, urlID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRepositoryInterfaceMockRecorder) Get(ctx, urlID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRepositoryInterface)(nil).Get), ctx, urlID)
}

// GetUserUrls mocks base method.
func (m *MockRepositoryInterface) GetUserUrls(ctx context.Context, userID int) (models.ApiUserUrlsRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserUrls", ctx, userID)
	ret0, _ := ret[0].(models.ApiUserUrlsRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserUrls indicates an expected call of GetUserUrls.
func (mr *MockRepositoryInterfaceMockRecorder) GetUserUrls(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserUrls", reflect.TypeOf((*MockRepositoryInterface)(nil).GetUserUrls), ctx, userID)
}

// GetUsersID mocks base method.
func (m *MockRepositoryInterface) GetUsersID(ctx context.Context) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersID", ctx)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersID indicates an expected call of GetUsersID.
func (mr *MockRepositoryInterfaceMockRecorder) GetUsersID(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetUsersID), ctx)
}

// Ping mocks base method.
func (m *MockRepositoryInterface) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockRepositoryInterfaceMockRecorder) Ping(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockRepositoryInterface)(nil).Ping), ctx)
}

// SetDelete mocks base method.
func (m *MockRepositoryInterface) SetDelete(ctx context.Context, ctxUUID string, isLastReq bool, userID int, urlID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDelete", ctx, ctxUUID, isLastReq, userID, urlID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetDelete indicates an expected call of SetDelete.
func (mr *MockRepositoryInterfaceMockRecorder) SetDelete(ctx, ctxUUID, isLastReq, userID, urlID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDelete", reflect.TypeOf((*MockRepositoryInterface)(nil).SetDelete), ctx, ctxUUID, isLastReq, userID, urlID)
}

// Store mocks base method.
func (m *MockRepositoryInterface) Store(ctx context.Context, ctxUUID string, isLastReq bool, userID int, urlID, url string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, ctxUUID, isLastReq, userID, urlID, url)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Store indicates an expected call of Store.
func (mr *MockRepositoryInterfaceMockRecorder) Store(ctx, ctxUUID, isLastReq, userID, urlID, url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockRepositoryInterface)(nil).Store), ctx, ctxUUID, isLastReq, userID, urlID, url)
}
