// cmd/reset/main.go
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

type templateData struct {
	Package string
	Structs []*templateStruct
}

type templateStruct struct {
	Name   string
	Fields []templateField
}

type templateField struct {
	Name      string
	Type      string
	ZeroValue string
	IsSlice   bool
	IsMap     bool
}

const resetTemplate = `// Code generated by reset generator; DO NOT EDIT.
// generate:reset

package {{.Package}}

{{range .Structs}}
func (rs *{{.Name}}) Reset() {
	if rs == nil {
		return
	}
{{range .Fields}}
{{- if .IsSlice}}
	rs.{{.Name}} = rs.{{.Name}}[:0]
{{- else if .IsMap}}
	clear(rs.{{.Name}})
{{- else}}
	rs.{{.Name}} = {{.ZeroValue}}
{{- end}}
{{end}}
}
{{end}}
`

var tmpl = template.Must(template.New("reset").Parse(resetTemplate))

func main() {
	if err := run(); err != nil {
		panic(err)
	}
}

func run() error {
	rootDir, err := os.Getwd()
	if err != nil {
		return err
	}
	packages, err := findPackagesWithResetStructs(rootDir)
	if err != nil {
		return err
	}
	for pkgPath, structs := range packages {
		if err := generateResetFile(pkgPath, structs); err != nil {
			return err
		}
	}
	return nil
}

func findPackagesWithResetStructs(rootDir string) (map[string][]*templateStruct, error) {
	packages := make(map[string][]*templateStruct)
	err := filepath.Walk(rootDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if !strings.HasSuffix(info.Name(), ".go") ||
			strings.HasSuffix(info.Name(), "_test.go") ||
			info.Name() == "reset.gen.go" {
			return nil
		}
		fset := token.NewFileSet()
		node, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if err != nil {
			return nil
		}
		var structs []*templateStruct
		ast.Inspect(node, func(n ast.Node) bool {
			switch x := n.(type) {
			case *ast.GenDecl:
				if x.Doc != nil {
					for _, comment := range x.Doc.List {
						if strings.Contains(comment.Text, "generate:reset") {
							for _, spec := range x.Specs {
								typeSpec, ok := spec.(*ast.TypeSpec)
								if !ok {
									continue
								}
								structType, ok := typeSpec.Type.(*ast.StructType)
								if !ok {
									continue
								}
								fields := parseStructFields(structType)
								structs = append(structs, &templateStruct{
									Name:   typeSpec.Name.Name,
									Fields: fields,
								})
							}
						}
					}
				}
			}
			return true
		})
		if len(structs) > 0 {
			pkgDir := filepath.Dir(path)
			relPath, err := filepath.Rel(rootDir, pkgDir)
			if err != nil {
				return err
			}
			if relPath == "." {
				relPath = ""
			}
			packages[relPath] = append(packages[relPath], structs...)
		}
		return nil
	})
	return packages, err
}

func parseStructFields(structType *ast.StructType) []templateField {
	var fields []templateField
	for _, field := range structType.Fields.List {
		for _, name := range field.Names {
			fieldType := getTypeString(field.Type)
			fieldInfo := templateField{
				Name:      name.Name,
				Type:      fieldType,
				ZeroValue: getZeroValue(fieldType),
				IsSlice:   strings.HasPrefix(fieldType, "[]"),
				IsMap:     strings.HasPrefix(fieldType, "map["),
			}
			fields = append(fields, fieldInfo)
		}
	}
	return fields
}

func getTypeString(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		return "*" + getTypeString(t.X)
	case *ast.ArrayType:
		if t.Len == nil {
			return "[]" + getTypeString(t.Elt)
		}
		return "[...]" + getTypeString(t.Elt)
	case *ast.MapType:
		return "map[" + getTypeString(t.Key) + "]" + getTypeString(t.Value)
	case *ast.SelectorExpr:
		return getTypeString(t.X) + "." + t.Sel.Name
	case *ast.InterfaceType:
		if t.Methods == nil || len(t.Methods.List) == 0 {
			return "interface{}"
		}
		return "interface{...}"
	case *ast.StructType:
		return "struct{...}"
	default:
		return fmt.Sprintf("%v", expr)
	}
}

func getZeroValue(typeName string) string {
	if strings.HasPrefix(typeName, "*") {
		return "nil"
	}
	if strings.HasPrefix(typeName, "[]") {
		return "nil"
	}
	if strings.HasPrefix(typeName, "map[") {
		return "nil"
	}
	if typeName == "error" || typeName == "interface{}" || strings.Contains(typeName, "interface") {
		return "nil"
	}
	switch typeName {
	case "int", "int8", "int16", "int32", "int64":
		return "0"
	case "uint", "uint8", "uint16", "uint32", "uint64", "uintptr":
		return "0"
	case "float32", "float64":
		return "0.0"
	case "complex64", "complex128":
		return "0"
	case "byte", "rune":
		return "0"
	case "string":
		return "\"\""
	case "bool":
		return "false"
	default:
		return "nil"
	}
}

func generateResetFile(pkgPath string, structs []*templateStruct) error {
	if len(structs) == 0 {
		return nil
	}
	pkgName := filepath.Base(pkgPath)
	if pkgName == "." || pkgName == "" {
		pkgName = "main"
	}
	data := templateData{
		Package: pkgName,
		Structs: structs,
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return err
	}

	bufFmt, err := format.Source(buf.Bytes())
	if err != nil {
		return err
	}
	outputPath := filepath.Join(pkgPath, "reset.gen.go")
	basename := strings.TrimSuffix(outputPath, filepath.Ext("reset.gen.go"))
	err = os.WriteFile(fmt.Sprintf("%s.go", basename), bufFmt, 0644)
	if err != nil {
		return err
	}
	return nil
}
